### ISSUE TITLE
Some questions while first run

### ISSUE THREAD

**Issue by davidlatwe** [mottosso/allspark#2]
Hi, @mottosso 
Here I list out what I have done and what I have bumped into in my first try out.
Hope you could shed some light :)

#### Start !

I have created a Python 2.7 environment and did `pip install bleeding-rez PySide`, with `REZ_PACKAGES_PATH` set ready.

#### 'PackageFamilyNotFoundError'

When I finally call `launchapp2.bat`, it raised `PackageFamilyNotFoundError`.
Then I think, maybe I should prepare some required packages ?

So I take a look at what `launchapp2.bat` was doing, and I found it was calling `rez` to step into `rez python-2 PySide` *(I did not set `LAUNCHAPP_REQUIRE`)* these packages *(env ?)* in order to run `launchapp2`. 

Then I run `$ rez-bind  --quickstart`, for getting those startup packages, and I move those newly generated packages to my `_SERVER_PACKAGES` path, now I have `rez` and `python-2` packages collected. 

Finally, since I already `pip` installed `PySide`, I changed `LAUNCHAPP_REQUIRE` to just `rez python-2` and try calling `launchapp2.bat` again.

#### PackageRequestError: Not a valid package name: ''

But something is not right ?
I can see the GUI is up, but it shows:

![image](https://user-images.githubusercontent.com/3357009/59216739-db588680-8bee-11e9-9fa3-87e0a3e7e7d7.png)

<details>
 <summary> Here's the error message </summary>

```
(rez-app) C:\Users\david\Dropbox\github\launchapp2>rez env rez python-2 -- python -m launchapp2 --root %LAUNCHAPP_ROOT% --verbose
==============================
 launchapp2 (1.1.33)
==============================
- Loading Rez..
- Loading Qt..
- Loading launchapp2..
------------------------------
INFO     launchapp2.control Booting..
Resetting..
INFO     launchapp2.control Resetting..
INFO     launchapp2.control Booting..
ERROR    launchapp2.control Could not find projects in C:\Users\david\rez-projects
ERROR    launchapp2.control Couldn't find any projects @ 'C:\Users\david\rez-projects'
INFO     launchapp2.control Ready
INFO     launchapp2.control Loading..
ERROR    launchapp2.control   File "launchapp2\control.py", line 432, in do
    project = self._find_project(project_name, version)
  File "launchapp2\control.py", line 536, in _find_project
    versions = sorted(it, key=lambda x: x.version, reverse=True)
  File "C:\Users\david\rez-app\.rez\packages\rez\2.29.9\platform-windows\arch-AMD64\os-windows-10.0.17134\rez\packages_.py", line 502, in iter_packages
    entries = _get_families(name, paths)
  File "C:\Users\david\rez-app\.rez\packages\rez\2.29.9\platform-windows\arch-AMD64\os-windows-10.0.17134\rez\packages_.py", line 754, in _get_families
    family_resource = repo.get_package_family(name)
  File "C:\Users\david\rez-app\.rez\packages\rez\2.29.9\platform-windows\arch-AMD64\os-windows-10.0.17134\rezplugins\package_repository\filesystem.py", line 491, in get_package_family
    return self.get_family(name)
  File "C:\Users\david\rez-app\.rez\packages\rez\2.29.9\platform-windows\arch-AMD64\os-windows-10.0.17134\rez\backport\lru_cache.py", line 74, in wrapper
    result = user_function(*args, **kwds)
  File "C:\Users\david\rez-app\.rez\packages\rez\2.29.9\platform-windows\arch-AMD64\os-windows-10.0.17134\rezplugins\package_repository\filesystem.py", line 786, in _get_family
    is_valid_package_name(name, raise_error=True)
  File "C:\Users\david\rez-app\.rez\packages\rez\2.29.9\platform-windows\arch-AMD64\os-windows-10.0.17134\rez\utils\formatting.py", line 39, in is_valid_package_name
    raise PackageRequestError("Not a valid package name: %r" % name)

ERROR    launchapp2.control Not a valid package name: ''
Traceback (most recent call last):
  File "launchapp2\control.py", line 432, in do
    project = self._find_project(project_name, version)
  File "launchapp2\control.py", line 536, in _find_project
    versions = sorted(it, key=lambda x: x.version, reverse=True)
  File "C:\Users\david\rez-app\.rez\packages\rez\2.29.9\platform-windows\arch-AMD64\os-windows-10.0.17134\rez\packages_.py", line 502, in iter_packages
    entries = _get_families(name, paths)
  File "C:\Users\david\rez-app\.rez\packages\rez\2.29.9\platform-windows\arch-AMD64\os-windows-10.0.17134\rez\packages_.py", line 754, in _get_families
    family_resource = repo.get_package_family(name)
  File "C:\Users\david\rez-app\.rez\packages\rez\2.29.9\platform-windows\arch-AMD64\os-windows-10.0.17134\rezplugins\package_repository\filesystem.py", line 491, in get_package_family
    return self.get_family(name)
  File "C:\Users\david\rez-app\.rez\packages\rez\2.29.9\platform-windows\arch-AMD64\os-windows-10.0.17134\rez\backport\lru_cache.py", line 74, in wrapper
    result = user_function(*args, **kwds)
  File "C:\Users\david\rez-app\.rez\packages\rez\2.29.9\platform-windows\arch-AMD64\os-windows-10.0.17134\rezplugins\package_repository\filesystem.py", line 786, in _get_family
    is_valid_package_name(name, raise_error=True)
  File "C:\Users\david\rez-app\.rez\packages\rez\2.29.9\platform-windows\arch-AMD64\os-windows-10.0.17134\rez\utils\formatting.py", line 39, in is_valid_package_name
    raise PackageRequestError("Not a valid package name: %r" % name)
rez.exceptions.PackageRequestError: Not a valid package name: ''
```

</details>

Do you have any ideas what's going on ?
And, will there be default (basic/startup) packages shipping with `launchapp2` ?

Thanks !

**Comment by mottosso** [comment]
Thanks for testing this so early, I'll cover these questions, and more, in the official docs. :)

https://allspark.sh/
